# Renkler ve Log Formatları
colors:
  SQL Injection: "red"
  Brute Force: "orange"
  Directory Traversal: "purple"
  Command Injection: "brown"
  XSS: "green"
  SQL Error: "pink"
  Suspicious User-Agent: "blue"
  Suspicious URL: "teal"
  RCE: "darkred"
  File Inclusion: "darkgreen"
  Password Spraying: "darkorange"
  Web Shell: "darkviolet"
  Information Disclosure: "gray"

log_formats:
  generic:
    # Log dosyanızdaki format için düzeltilmiş regex
    regex: '^(?P<zaman>\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})\s+(?P<ip>\S+)\s+(?P<method>\S+)\s+(?P<url>\S+)\s+\S+\s+(?P<status>\d+)\s+.*'
  nginx:
    # Nginx log formatı için regex
    regex: '^(?P<ip>\S+)\s+-\s+-\s+\[(?P<zaman>.*?)\]\s+"(?P<method>\S+)\s+(?P<url>\S+)\s+\S+"\s+(?P<status>\d+).*'

# Saldırı Tespit Kuralları
patterns:
  SQL Injection:
    - regex: "(\\'\\s*or\\s*\\'1\\'\\s*=\\s*\\'1|\\'\\s*or\\s*1\\s*=\\s*1)"
      severity: "Yüksek"
      description: "AND/OR veya eşittir işaretleri içeren temel SQL enjeksiyon denemesi."
      recommendation: "Giriş doğrulamayı ve parametreli sorguları kontrol edin."
    - regex: "union\\s+select"
      severity: "Yüksek"
      description: "Veritabanı tablolarını birleştirmeyi amaçlayan UNION SELECT enjeksiyonu."
      recommendation: "Giriş doğrulamayı ve parametreli sorguları kontrol edin."
    - regex: "\\'--"
      severity: "Yüksek"
      description: "SQL yorum satırı ile sorguyu manipüle etme denemesi."
      recommendation: "Giriş doğrulamayı ve parametreli sorguları kontrol edin."
    - regex: "\\bexec\\b"
      severity: "Kritik"
      description: "Veritabanı üzerinde komut çalıştırma denemesi (genel)."
      recommendation: "Veritabanı izinlerini ve uygulama kodunu kontrol edin."
    - regex: "drop\\s+table"
      severity: "Kritik"
      description: "Veritabanı tablosu silme denemesi."
      recommendation: "Veritabanı izinlerini ve uygulama kodunu kontrol edin."
    - regex: "sleep\\(\\d+\\)"
      severity: "Yüksek"
      description: "Sorgu performansını etkileyerek bilgi sızdırma denemesi (Zaman Tabanlı Kör SQLi)."
      recommendation: "Zaman bazlı anormallikleri izleyin ve girişleri sıkı doğrulayın."
    - regex: "benchmark\\("
      severity: "Yüksek"
      description: "Zaman bazlı Kör SQLi için Benchmark fonksiyonu kullanımı."
      recommendation: "Zaman bazlı anormallikleri izleyin ve girişleri sıkı doğrulayın."
    - regex: "extractvalue\\("
      severity: "Yüksek"
      description: "ExtractValue fonksiyonu ile hata tabanlı bilgi sızdırma denemesi."
      recommendation: "Hata mesajlarını kullanıcıya göstermekten kaçının ve girişleri doğrulayın."
    - regex: "updatexml\\("
      severity: "Yüksek"
      description: "UpdateXML fonksiyonu ile hata tabanlı bilgi sızdırma denemesi."
      recommendation: "Hata mesajlarını kullanıcıya göstermekten kaçının ve girişleri doğrulayın."
    - regex: "\\bconvert\\b\\s*\\("
      severity: "Yüksek"
      description: "CONVERT fonksiyonu ile hata tabanlı bilgi sızdırma denemesi."
      recommendation: "Hata mesajlarını kullanıcıya göstermekten kaçının ve girişleri doğrulayın."
    - regex: "\\bdeclare\\b\\s*@\\w+\\s+varchar"
      severity: "Yüksek"
      description: "Yığınlanmış sorgular ile komut çalıştırma denemesi (MSSQL)."
      recommendation: "Parametreli sorguları kullanın, çoklu sorgu yürütmeyi kısıtlayın."
    - regex: "xp_cmdshell"
      severity: "Kritik"
      description: "MSSQL'de işletim sistemi komutu çalıştırma denemesi."
      recommendation: "Veritabanı izinlerini ve xp_cmdshell'in devre dışı bırakıldığını kontrol edin."
    - regex: "LOAD_FILE\\("
      severity: "Kritik"
      description: "MySQL'de dosya okuma denemesi (LOAD_FILE)."
      recommendation: "MySQL'de LOCAL_INFILE ayarını devre dışı bırakın."
    - regex: "into\\s+outfile"
      severity: "Kritik"
      description: "MySQL'de dosya yazma denemesi (INTO OUTFILE)."
      recommendation: "MySQL'de INTO OUTFILE kullanımını denetleyin, dosya yazma izinlerini kısıtlayın."
    - regex: "\\bpg_sleep\\(\\d+\\)"
      severity: "Yüksek"
      description: "PostgreSQL'de zaman tabanlı kör SQLi denemesi."
      recommendation: "Zaman bazlı anormallikleri izleyin ve girişleri sıkı doğrulayın."
  Brute Force:
    - regex: "failed\\s+login"
      severity: "Orta"
      description: "Başarısız giriş denemesi."
      recommendation: "Hesap kilitleme ve CAPTCHA uygulamasını gözden geçirin."
    - regex: "authentication\\s+failure"
      severity: "Orta"
      description: "Kimlik doğrulama hatası."
      recommendation: "Hesap kilitleme ve CAPTCHA uygulamasını gözden geçirin."
    - regex: "login\\s+failed"
      severity: "Orta"
      description: "Kullanıcı adı/şifre eşleşmedi."
      recommendation: "Hesap kilitleme ve CAPTCHA uygulamasını gözden geçirin."
    - regex: "password\\s+incorrect"
      severity: "Orta"
      description: "Yanlış şifre girildi."
      recommendation: "Hesap kilitleme ve CAPTCHA uygulamasını gözden geçirin."
    - regex: "login\\s+failed\\s+for\\s+user"
      severity: "Orta"
      description: "Belirli bir kullanıcı için başarısız giriş denemesi."
      recommendation: "Hesap kilitleme ve CAPTCHA uygulamasını gözden geçirin."
    - regex: "401"
      severity: "Orta"
      description: "HTTP 401 Unauthorized - Kimlik doğrulama başarısız."
      recommendation: "Hesap kilitleme ve CAPTCHA uygulamasını gözden geçirin."
  Directory Traversal:
    - regex: "\\.\\./"
      severity: "Yüksek"
      description: "Dizin dışına çıkma denemesi (../)."
      recommendation: "Yol doğrulamasını ve kullanıcı girişini temizlemeyi sağlayın."
    - regex: "%2e%2e%2f"
      severity: "Yüksek"
      description: "URL kodlu dizin dışına çıkma denemesi (../)."
      recommendation: "URL kod çözme sonrası yol doğrulamasını sağlayın."
    - regex: "etc/passwd"
      severity: "Yüksek"
      description: "Sistem hassas dosyalarına erişim denemesi."
      recommendation: "Dizin kısıtlamalarını ve dosya izinlerini kontrol edin."
    - regex: "php://filter"
      severity: "Yüksek"
      description: "PHP filtreleri ile dosya okuma denemesi."
      recommendation: "PHP ayarlarını ve dosya yükleme izinlerini kontrol edin."
  Command Injection:
    - regex: "\\|"
      severity: "Kritik"
      description: "Komut ayırıcı (|) kullanımı ile komut enjeksiyonu."
      recommendation: "Kullanıcı girdisini filtreleyin ve shell komutları yerine API kullanın."
    - regex: ";"
      severity: "Kritik"
      description: "Komut ayırıcı (;) kullanımı ile komut enjeksiyonu."
      recommendation: "Kullanıcı girdisini filtreleyin ve shell komutları yerine API kullanın."
    - regex: "&&"
      severity: "Kritik"
      description: "Komut birleştirme (&&) kullanımı ile komut enjeksiyonu."
      recommendation: "Kullanıcı girdisini filtreleyin ve shell komutları yerine API kullanın."
    - regex: "wget\\s"
      severity: "Yüksek"
      description: "Harici dosya indirme aracı (wget) kullanımı."
      recommendation: "Çalıştırılabilir komutları kısıtlayın."
    - regex: "curl\\s"
      severity: "Yüksek"
      description: "Harici dosya indirme aracı (curl) kullanımı."
      recommendation: "Çalıştırılabilir komutları kısıtlayın."
    - regex: "system\\("
      severity: "Kritik"
      description: "Sistem komutu çalıştırma fonksiyonu (system()) kullanımı."
      recommendation: "Kodda güvenli olmayan fonksiyon kullanımlarını denetleyin."
    - regex: "exec\\("
      severity: "Kritik"
      description: "Harici program çalıştırma fonksiyonu (exec()) kullanımı."
      recommendation: "Kodda güvenli olmayan fonksiyon kullanımlarını denetleyin."
    - regex: "passthru\\("
      severity: "Kritik"
      description: "Harici program çalıştırma fonksiyonu (passthru()) kullanımı."
      recommendation: "Kodda güvenli olmayan fonksiyon kullanımlarını denetleyin."
  XSS:
    - regex: "<script.*?>"
      severity: "Orta"
      description: "Temel HTML script etiketi enjeksiyonu."
      recommendation: "Çıkış kodlamasını ve içerik güvenliği politikasını (CSP) uygulayın."
    - regex: "onerror="
      severity: "Orta"
      description: "Hata olay işleyicisi ile XSS denemesi."
      recommendation: "Çıkış kodlamasını ve içerik güvenliği politikasını (CSP) uygulayın."
    - regex: "alert\\(.*\\)"
      severity: "Orta"
      description: "JavaScript alert fonksiyonu ile XSS denemesi."
      recommendation: "Çıkış kodlamasını ve içerik güvenliği politikasını (CSP) uygulayın."
  SQL Error:
    - regex: "SQL\\s+syntax"
      severity: "Düşük"
      description: "Genel SQL sözdizimi hatası göstergesi."
      recommendation: "Hata mesajlarını kullanıcıya göstermekten kaçının, loglara kaydedin."
    - regex: "mysql_fetch"
      severity: "Düşük"
      description: "MySQL ile ilgili hata mesajı."
      recommendation: "Hata mesajlarını kullanıcıya göstermekten kaçının, loglara kaydedin."
    - regex: "odbc_exec"
      severity: "Düşük"
      description: "ODBC ile ilgili hata mesajı."
      recommendation: "Hata mesajlarını kullanıcıya göstermekten kaçının, loglara kaydedin."
  Suspicious User-Agent:
    - regex: "curl"
      severity: "Düşük"
      description: "Curl aracı ile yapılan istek."
      recommendation: "Normal olmayan User-Agent'ları izleyin."
    - regex: "wget"
      severity: "Düşük"
      description: "Wget aracı ile yapılan istek."
      recommendation: "Normal olmayan User-Agent'ları izleyin."
    - regex: "sqlmap"
      severity: "Yüksek"
      description: "Otomatik SQL enjeksiyon aracı (sqlmap) kullanımı."
      recommendation: "Web uygulama güvenlik duvarı (WAF) kullanın."
    - regex: "nikto"
      severity: "Yüksek"
      description: "Web sunucusu tarama aracı (Nikto) kullanımı."
      recommendation: "Web uygulama güvenlik duvarı (WAF) kullanın."
  Suspicious URL:
    - regex: "\\?id=\\d+"
      severity: "Düşük"
      description: "ID parametresi içeren şüpheli URL deseni."
      recommendation: "Sıkı giriş doğrulama ve yetkilendirme kontrolü uygulayın."
    - regex: "\\?page="
      severity: "Düşük"
      description: "Page parametresi içeren şüpheli URL deseni."
      recommendation: "Sıkı giriş doğrulama ve yetkilendirme kontrolü uygulayın."
    - regex: "select.*from"
      severity: "Yüksek"
      description: "URL içinde SQL SELECT FROM ifadeleri."
      recommendation: "Web uygulama güvenlik duvarı (WAF) kullanın, URL normalleştirmesi yapın."
    - regex: "union.*select"
      severity: "Yüksek"
      description: "URL içinde SQL UNION SELECT ifadeleri."
      recommendation: "Web uygulama güvenlik duvarı (WAF) kullanın, URL normalleştirmesi yapın."
  RCE:
    - regex: "system\\("
      severity: "Kritik"
      description: "Uzak kod çalıştırma (RCE) denemesi: system() fonksiyonu."
      recommendation: "Kullanıcı girdisini asla doğrudan komutlara iletmeyin."
    - regex: "exec\\("
      severity: "Kritik"
      description: "Uzak kod çalıştırma (RCE) denemesi: exec() fonksiyonu."
      recommendation: "Kullanıcı girdisini asla doğrudan komutlara iletmeyin."
    - regex: "passthru\\("
      severity: "Kritik"
      description: "Uzak kod çalıştırma (RCE) denemesi: passthru() fonksiyonu."
      recommendation: "Kullanıcı girdisini asla doğrudan komutlara iletmeyin."
    - regex: "shell_exec\\("
      severity: "Kritik"
      description: "Uzak kod çalıştırma (RCE) denemesi: shell_exec() fonksiyonu."
      recommendation: "Kullanıcı girdisini asla doğrudan komutlara iletmeyin."
  File Inclusion:
    - regex: "include\\("
      severity: "Yüksek"
      description: "Yerel/Uzak dosya dahil etme (LFI/RFI) denemesi: include() fonksiyonu."
      recommendation: "Dış kaynakları dahil etmeyin, beyaz liste kullanın."
    - regex: "require\\("
      severity: "Yüksek"
      description: "Yerel/Uzak dosya dahil etme (LFI/RFI) denemesi: require() fonksiyonu."
      recommendation: "Dış kaynakları dahil etmeyin, beyaz liste kullanın."
    - regex: "php://"
      severity: "Yüksek"
      description: "PHP akış sarmalayıcıları ile dosya erişimi denemesi."
      recommendation: "PHP ayarlarında allow_url_include=Off yapın."
  Password Spraying:
    - regex: "password\\s+incorrect"
      severity: "Orta"
      description: "Çoklu kullanıcılar üzerinde aynı şifre deneme (password spraying) belirtisi."
      recommendation: "Başarısız giriş denemelerini izleyin ve anomalileri tespit edin."
    - regex: "login\\s+failed\\s+for\\s+user"
      severity: "Orta"
      description: "Çoklu kullanıcılar üzerinde başarısız giriş denemeleri."
      recommendation: "Başarısız giriş denemelerini izleyin ve anomalileri tespit edin."
    - regex: "authentication\\s+failure"
      severity: "Orta"
      description: "Çoklu kimlik doğrulama hatası."
      recommendation: "Başarısız giriş denemelerini izleyin ve anomalileri tespit edin."
  Web Shell:
    - regex: "cmd="
      severity: "Kritik"
      description: "URL'de komut yürütme parametresi (cmd) bulunması, web shell aktivitesine işaret edebilir."
      recommendation: "Web sunucunuzda web shell taraması yapın ve şüpheli dosya yüklemelerini kontrol edin."
    - regex: "eval\\("
      severity: "Kritik"
      description: "Eval fonksiyonunun loglarda görülmesi, dinamik kod yürütme denemesi olabilir."
      recommendation: "Uygulama kodunu inceleyin, eval kullanımından kaçının veya sıkıca denetleyin."
    - regex: "shell_exec\\("
      severity: "Kritik"
      description: "Web sunucusu üzerinden shell komutu çalıştırma denemesi."
      recommendation: "Web sunucunuzda web shell taraması yapın ve uygulama izinlerini gözden geçirin."
    - regex: "passthru\\("
      severity: "Kritik"
      description: "Web sunucusu üzerinden passthru komutu çalıştırma denemesi."
      recommendation: "Web sunucunuzda web shell taraması yapın ve uygulama izinlerini gözden geçirin."
    - regex: "system\\("
      severity: "Kritik"
      description: "Web sunucusu üzerinden system komutu çalıştırma denemesi."
      recommendation: "Web sunucunuzda web shell taraması yapın ve uygulama izinlerini gözden geçirin."
    - regex: "\\.php\\?.*="
      severity: "Yüksek"
      description: "Şüpheli PHP dosyası çağrıları, LFI/RFI veya web shell yüklemesi olabilir."
      recommendation: "Sunucudaki PHP dosyalarını inceleyin, web shell taraması yapın."
  Information Disclosure:
    - regex: "\\bconfig\\b"
      severity: "Yüksek"
      description: "Yapılandırma dosyalarına erişim denemesi (örn: config.php, web.config)."
      recommendation: "Hassas dosyaların web üzerinden erişimini kısıtlayın, dizin listelemeyi kapatın."
    - regex: "\\b\\.env\\b"
      severity: "Yüksek"
      description: "Çevre değişkenleri dosyasını ('.env') okuma denemesi."
      recommendation: ".env dosyasının web kök dizini dışında olduğundan emin olun."
    - regex: "\\b\\.git/config\\b"
      severity: "Orta"
      description: "Git deposu yapılandırma dosyasına erişim denemesi."
      recommendation: "Üretim ortamında .git dizinini kaldırın veya erişimi engelleyin."
    - regex: "\\bphpinfo\\(\\)"
      severity: "Düşük"
      description: "phpinfo() çağrısı ile sistem bilgisi toplama denemesi."
      recommendation: "phpinfo() kullanımını üretim ortamlarında devre dışı bırakın veya kaldırın."
